import {expect,test,type APIRequestContext,type Page} from '@playwright/test';
import {createLocalWorkflowFixture} from '../helpers/local-workflow-fixture.mjs';
async function fixtureFor(request:APIRequestContext,withReaffirmed:'pending'|'confirmed',withSameIntent=false) {
 const projects=await(await request.get('/api/v1/projects')).json(),events=await(await request.get(`/api/v1/projects/${projects.data.projects[0].id}/events`)).json(),current=await(await request.get(`/api/v2/events/${events.data.events[0].id}/workspace`)).json();return createLocalWorkflowFixture(current.data.access.workspaceId,{withReaffirmed,withSameIntent});
}
async function open(page:Page,f:Awaited<ReturnType<typeof fixtureFor>>) {await page.goto(`/?project=${f.projectId}&event=${f.repeatEventId}&view=simple`);await expect(page.getByRole('button',{name:'复制记录',exact:true})).toBeVisible();}
const snapshot=async(request:APIRequestContext,eventId:string)=>(await(await request.get(`/api/v2/events/${eventId}/workspace`)).json()).data;
test('pending repeat is readable and copyable with its current source without duplicate adoption',async({page,request},info)=>{
 const f=await fixtureFor(request,'pending');try{await open(page,f);const row=page.getByTestId(`mention-${f.repeatBudgetId}`);await expect(row).toContainText('预算大约三十万');await expect(row).toContainText('关联待核对');await expect(page.getByText('材料整理好后，重点会出现在这里。')).toHaveCount(0);await expect(page.getByRole('button',{name:'加入跟进',exact:true})).toHaveCount(0);await row.locator('summary').click();await expect(row.getByText(/预算仍然大约三十万/)).toBeVisible();const saved=page.waitForResponse(r=>r.url().endsWith(`/api/v2/projects/${f.projectId}/reports`) && r.request().method()==='POST');await page.getByRole('button',{name:'复制记录',exact:true}).click();expect((await(await saved).json()).data.content).toContain('AI 关联待核对');if(await page.getByRole('dialog').count())await page.getByRole('dialog').getByRole('button',{name:'返回记录',exact:true}).click();await page.screenshot({path:info.outputPath('pending-repeat-reading.png'),fullPage:true});await row.getByRole('link',{name:'查看原事项',exact:true}).click();await expect(page.getByTestId(`bullet-${f.budgetId}`)).toBeVisible();expect(new URL(page.url()).searchParams.get('event')).toBe(f.eventId);
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
test('confirmed repeats preserve one original action and question through completion and an answer',async({page,request},info)=>{
 const f=await fixtureFor(request,'confirmed');try{await open(page,f);await expect(page.getByTestId(`mention-${f.repeatBudgetId}`)).toContainText('沿用原事项');await expect(page.getByRole('button',{name:'加入跟进',exact:true})).toHaveCount(0);await page.getByRole('button',{name:/^完成：/}).click();await expect(page.getByRole('button',{name:/^重开：/})).toBeVisible();let w=await snapshot(request,f.repeatEventId!);expect(w.actions).toHaveLength(1);expect(w.actions[0].id).toBe(f.actionId);expect(w.questions[0].resolutionState).toBe('open');await page.getByRole('button',{name:'补答案',exact:true}).click();await page.getByLabel('补充答案',{exact:true}).fill('供应商报价十二万元');await page.getByRole('button',{name:'保存答案',exact:true}).click();await expect(page.getByRole('button',{name:'更新答案',exact:true})).toBeVisible();w=await snapshot(request,f.repeatEventId!);expect(w.actions[0].executionState).toBe('completed');expect(w.questions[0].resolutionState).toBe('resolved');expect((await snapshot(request,f.eventId)).questions[0].resolutionState).toBe('resolved');await page.screenshot({path:info.outputPath('confirmed-repeat-loop.png'),fullPage:true});await page.reload();await expect(page.getByRole('button',{name:/^重开：/})).toBeVisible();await expect(page.getByRole('button',{name:'更新答案',exact:true})).toBeVisible();
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
test('changed current source conceals the repeated quote and does not serve the prior cached body',async({page,request},info)=>{
 const f=await fixtureFor(request,'pending');try{await open(page,f);const row=page.getByTestId(`mention-${f.repeatBudgetId}`);await row.locator('summary').click();await expect(row.getByText(/预算仍然大约三十万/)).toBeVisible();f.replaceRepeatedSource();await page.reload();await expect(page.getByTestId(`mention-${f.repeatBudgetId}`)).toContainText('本次出处已变化');await page.getByTestId(`mention-${f.repeatBudgetId}`).locator('summary').click();await expect(page.getByText(/预算仍然大约三十万/)).toHaveCount(0);expect((await snapshot(request,f.repeatEventId!)).reaffirmedMentions[0].sourceStatus).toBe('stale');await page.screenshot({path:info.outputPath('repeat-source-changed.png'),fullPage:true});
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
test('the optional association can be confirmed and undone from the actual new record',async({page,request},info)=>{
 const f=await fixtureFor(request,'pending');try{await open(page,f);let row=page.getByTestId(`mention-${f.repeatBudgetId}`);await row.locator('summary').click();await row.getByRole('button',{name:'沿用原事项',exact:true}).click();await expect(page.getByTestId(`bullet-${f.budgetId}`)).toContainText('已采纳');let w=await snapshot(request,f.repeatEventId!);expect(w.bullets).toHaveLength(1);expect(w.bullets[0].id).toBe(f.budgetId);expect(w.reaffirmedMentions[0].associationState).toBe('confirmed');await page.reload();await expect(page.getByTestId(`bullet-${f.budgetId}`)).toBeVisible();await page.getByRole('button',{name:'撤销上次处理',exact:true}).click();row=page.getByTestId(`mention-${f.repeatBudgetId}`);await expect(row).toContainText('关联待核对');w=await snapshot(request,f.repeatEventId!);expect(w.bullets).toHaveLength(0);expect((await snapshot(request,f.eventId)).bullets.find((b:{id:string})=>b.id===f.budgetId).reviewState).toBe('accepted');await row.locator('summary').click();await page.screenshot({path:info.outputPath('optional-association-controls.png'),fullPage:true});
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
test('an independent draft can be undone, reviewed and accepted while its later acceptance protects the association history',async({page,request},info)=>{
 const f=await fixtureFor(request,'pending');try{await open(page,f);let row=page.getByTestId(`mention-${f.repeatBudgetId}`);await row.locator('summary').click();await row.getByRole('button',{name:'作为独立信息',exact:true}).click();let w=await snapshot(request,f.repeatEventId!);expect(w.bullets).toHaveLength(1);expect(w.bullets[0].reviewState).toBe('draft');expect(w.bullets[0].id).not.toBe(f.budgetId);await expect(page.getByRole('button',{name:'确认这条',exact:true})).toBeVisible();await page.getByRole('button',{name:'撤销上次处理',exact:true}).click();row=page.getByTestId(`mention-${f.repeatBudgetId}`);await row.locator('summary').click();await row.getByRole('button',{name:'作为独立信息',exact:true}).click();await page.getByRole('button',{name:'确认这条',exact:true}).click();w=await snapshot(request,f.repeatEventId!);expect(w.bullets[0].reviewState).toBe('accepted');const association=w.recentDecisions.find((d:{operation:string;reverted:boolean})=>d.operation==='convert_mention'&&!d.reverted);await page.locator('summary').filter({hasText:'最近处理'}).click();await page.getByTestId(`decision-${association.id}`).getByRole('button',{name:'撤销',exact:true}).click();await expect(page.getByRole('alert').filter({hasText:'独立信息已有后续处理'})).toBeVisible();expect((await snapshot(request,f.repeatEventId!)).bullets[0].reviewState).toBe('accepted');await page.screenshot({path:info.outputPath('independent-draft-reviewed.png'),fullPage:true});
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
test('ignoring a proposed repeat is reversible and leaves its original item accepted',async({page,request},info)=>{
 const f=await fixtureFor(request,'pending');try{await open(page,f);const row=page.getByTestId(`mention-${f.repeatBudgetId}`);await row.locator('summary').click();await row.getByRole('button',{name:'忽略',exact:true}).click();await expect(row).toHaveCount(0);expect((await snapshot(request,f.eventId)).bullets.find((b:{id:string})=>b.id===f.budgetId).reviewState).toBe('accepted');await page.getByRole('button',{name:'撤销上次处理',exact:true}).click();await expect(row).toContainText('关联待核对');await page.reload();await expect(row).toContainText('关联待核对');await page.screenshot({path:info.outputPath('ignored-association-restored.png'),fullPage:true});
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
test('a repeated action in a shared original decision keeps one review entry',async({page,request},info)=>{
 const f=await fixtureFor(request,'confirmed',true);try{
  const old=await snapshot(request,f.eventId),later=await snapshot(request,f.repeatEventId!);
  expect(old.reviewCards.filter((c:{memberRefs:{claimId:string}[]})=>c.memberRefs.some(r=>r.claimId===f.actionId)).map((c:{id:string})=>c.id)).toEqual([f.intentCardId]);
  expect(later.reviewCards.some((c:{id:string})=>c.id===`wfc_${f.actionId}`)).toBe(false);
  expect(later.actions.map((a:{id:string})=>a.id)).toEqual([f.actionId]);
  await open(page,f);
  await expect(page.getByTestId(`mention-${f.repeatActionId}`)).toContainText('沿用原事项');
  await expect(page.locator(`[data-review-card="wfc_${f.actionId}"]`)).toHaveCount(0);
  await expect(page.getByRole('button',{name:'加入跟进',exact:true})).toHaveCount(0);
  await page.screenshot({path:info.outputPath('grouped-action-repeated-on-new-record.png'),fullPage:true});
  await page.goto(`/?project=${f.projectId}&event=${f.eventId}&view=simple`);
  await expect(page.locator(`[data-review-card="${f.intentCardId}"]`)).toHaveCount(1);
  await expect(page.locator(`[data-review-card="wfc_${f.actionId}"]`)).toHaveCount(0);
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
