import {expect,test,type APIRequestContext,type Page} from '@playwright/test';
import {createLocalWorkflowFixture} from '../helpers/local-workflow-fixture.mjs';
async function fixtureFor(request:APIRequestContext) {
 const projects=await (await request.get('/api/v1/projects')).json();const events=await (await request.get(`/api/v1/projects/${projects.data.projects[0].id}/events`)).json();const current=await (await request.get(`/api/v2/events/${events.data.events[0].id}/workspace`)).json();return createLocalWorkflowFixture(current.data.access.workspaceId,{withActionConflict:true});
}
async function open(page:Page,f:Awaited<ReturnType<typeof fixtureFor>>) {await page.goto(`/?project=${f.projectId}&event=${f.eventId}&view=simple`);await expect(page.getByRole('button',{name:'复制记录',exact:true})).toBeVisible();await page.getByTestId(`bullet-${f.actionId}`).getByRole('button',{name:'加入跟进',exact:true}).click();}
async function complete(page:Page) {await page.getByRole('button',{name:'补结果',exact:true}).click();await page.getByLabel('补充答案',{exact:true}).fill('供应商报价十二万元。');await page.getByLabel('同时标记行动完成',{exact:true}).check();await page.getByRole('button',{name:'保存结果',exact:true}).click();await expect(page.getByRole('button',{name:'重开：向供应商询价',exact:true})).toBeVisible();}
async function review(page:Page) {await page.getByRole('button',{name:'核对新旧信息',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('决定接下来跟进哪项');}
async function footerVisible(page:Page) {const box=await page.getByRole('button',{name:'保存选择',exact:true}).boundingBox();expect(box!.y+box!.height).toBeLessThanOrEqual(page.viewportSize()!.height);}

test('a new action replaces the current follow-up while original completion and result remain readable',async({page,request},info)=>{
 const f=await fixtureFor(request);try{await open(page,f);await complete(page);await review(page);await expect(page.getByRole('dialog')).toContainText('当时已完成');await page.getByRole('radio',{name:/改为跟进新行动/}).check();await footerVisible(page);await page.screenshot({path:info.outputPath('action-replacement-review.png'),fullPage:false});await page.getByRole('button',{name:'保存选择',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'完成：向厂家确认交期',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'重开：向供应商询价',exact:true})).toHaveCount(0);await page.getByTestId('action-history').getByText('已替代的跟进',{exact:false}).click();const history=page.getByTestId(`historical-action-${f.actionId}`);await expect(history).toContainText('当时已完成');await expect(history).toContainText('供应商报价十二万元');await expect(history).toContainText('现在跟进：向厂家确认交期');await expect(history.getByRole('button')).toHaveCount(0);await page.screenshot({path:info.outputPath('action-replacement-history.png'),fullPage:true});
 const current=(await (await request.get(`/api/v2/events/${f.eventId}/workspace`)).json()).data;expect(current.actions[0].latestOutcome).toBeNull();expect(current.questions[0].resolutionState).toBe('resolved');
 await page.getByRole('button',{name:'撤销上次处理',exact:true}).click();await expect(page.getByRole('button',{name:'重开：向供应商询价',exact:true})).toBeVisible();await expect(page.getByTestId('action-history')).toHaveCount(0);await expect(page.getByRole('button',{name:'核对新旧信息',exact:true})).toBeVisible();
 await review(page);await page.getByRole('radio',{name:/改为跟进新行动/}).check();await page.getByRole('button',{name:'保存选择',exact:true}).click();await page.getByRole('button',{name:'撤回答案',exact:true}).click();await page.getByRole('button',{name:'确认撤回',exact:true}).click();await expect(page.getByRole('button',{name:'补答案',exact:true})).toBeVisible();await page.getByTestId('action-history').getByText('已替代的跟进',{exact:false}).click();await expect(page.getByTestId(`historical-action-${f.actionId}`)).toContainText('当时已完成');await expect(page.getByRole('button',{name:'完成：向厂家确认交期',exact:true})).toBeVisible();
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
test('two follow-ups retain separate execution states and explicit applicability',async({page,request},info)=>{
 const f=await fixtureFor(request);try{await open(page,f);await complete(page);await review(page);await page.getByRole('radio',{name:/两项都跟进/}).check();await page.getByRole('textbox',{name:'适用情况',exact:true}).fill('供应商负责报价，厂家负责交期。');await page.getByRole('dialog').getByRole('button',{name:'关闭',exact:true}).click();await expect(page.getByText('这次选择还未保存。',{exact:true})).toBeVisible();await page.getByRole('button',{name:'继续核对',exact:true}).click();await expect(page.getByRole('textbox',{name:'适用情况',exact:true})).toHaveValue('供应商负责报价，厂家负责交期。');await footerVisible(page);await page.screenshot({path:info.outputPath('action-coexist-review.png'),fullPage:false});await page.getByRole('button',{name:'保存选择',exact:true}).click();await expect(page.getByRole('button',{name:'重开：向供应商询价',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'完成：向厂家确认交期',exact:true})).toBeVisible();await expect(page.getByTestId('action-history')).toHaveCount(0);await expect(page.getByTestId(`bullet-${f.newActionId}`)).toContainText('供应商负责报价');await page.screenshot({path:info.outputPath('action-coexist.png'),fullPage:true});await page.getByRole('button',{name:'撤销上次处理',exact:true}).click();await expect(page.getByRole('button',{name:'完成：向厂家确认交期',exact:true})).toHaveCount(0);
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
test('keeping the original leaves its completion and answer intact and rejects the new suggestion',async({page,request})=>{
 const f=await fixtureFor(request);try{await open(page,f);await complete(page);await review(page);await page.getByRole('radio',{name:/继续原行动/}).check();await page.getByRole('button',{name:'保存选择',exact:true}).click();await expect(page.getByTestId(`bullet-${f.newActionId}`)).toHaveCount(0);await expect(page.getByRole('button',{name:'重开：向供应商询价',exact:true})).toBeVisible();await expect(page.getByText('供应商报价十二万元。',{exact:true}).first()).toBeVisible();await page.getByRole('button',{name:'撤销上次处理',exact:true}).click();await expect(page.getByRole('button',{name:'核对新旧信息',exact:true})).toBeVisible();
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
test('a concurrent execution change requires reviewing the latest original action before replacement',async({page,request},info)=>{
 const f=await fixtureFor(request);try{await open(page,f);await complete(page);await review(page);await page.getByRole('radio',{name:/改为跟进新行动/}).check();const current=(await (await request.get(`/api/v2/events/${f.eventId}/workspace`)).json()).data,a=current.actions[0];const res=await request.post(`/api/v2/actions/${a.id}/transitions`,{headers:{'Idempotency-Key':crypto.randomUUID()},data:{expectedContextVersion:current.contextVersion,expectedActionRevision:a.revision,operation:'reopen'}});expect(res.ok()).toBe(true);await page.getByRole('button',{name:'保存选择',exact:true}).click();await expect(page.getByRole('button',{name:'重新核对最新内容',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'保存选择',exact:true})).toBeDisabled();await page.getByRole('button',{name:'重新核对最新内容',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('待跟进');await footerVisible(page);await page.screenshot({path:info.outputPath('action-concurrent-review.png'),fullPage:false});await page.getByRole('button',{name:'保存选择',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.getByTestId('action-history').getByText('已替代的跟进',{exact:false}).click();await expect(page.getByTestId(`historical-action-${f.actionId}`)).toContainText('当时待跟进');
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
