import {expect,test,type APIRequestContext,type Page} from '@playwright/test';
import {createLocalWorkflowFixture} from '../helpers/local-workflow-fixture.mjs';
async function fixtureFor(request:APIRequestContext,withIntentConflict:false|'record'|'action'=false) {
 const projects=await (await request.get('/api/v1/projects')).json(),events=await (await request.get(`/api/v1/projects/${projects.data.projects[0].id}/events`)).json(),current=await (await request.get(`/api/v2/events/${events.data.events[0].id}/workspace`)).json();return createLocalWorkflowFixture(current.data.access.workspaceId,{withSameIntent:true,withIntentConflict});
}
async function open(page:Page,f:Awaited<ReturnType<typeof fixtureFor>>){await page.goto(`/?project=${f.projectId}&event=${f.eventId}&view=simple`);await expect(page.getByRole('button',{name:'复制记录',exact:true})).toBeVisible();}
const snap=async(request:APIRequestContext,eventId:string)=>(await (await request.get(`/api/v2/events/${eventId}/workspace`)).json()).data;

test('one agreement has one visible choice and recording alone leaves the action unfollowed',async({page,request},info)=>{
 const f=await fixtureFor(request);try{await open(page,f);const row=page.locator(`[data-review-card="${f.intentCardId}"]`);await expect(row).toHaveCount(1);await expect(page.getByRole('button',{name:'加入跟进',exact:true})).toHaveCount(1);await expect(page.getByRole('button',{name:'确认记录',exact:true})).toBeVisible();await page.getByRole('button',{name:'确认记录',exact:true}).click();await expect(page.getByTestId(`bullet-${f.agreementId}`)).toBeVisible();const w=await snap(request,f.eventId);expect(w.actions).toHaveLength(0);expect(w.counts.needsDecisionCount).toBe(0);expect(w.reviewCards.find((c:{id:string})=>c.id===f.intentCardId).members.find((m:{claimId:string})=>m.claimId===f.actionId).reviewState).toBe('draft');await expect(page.getByRole('button',{name:'补答案',exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('record-only-intent.png'),fullPage:true});await page.reload();await expect(page.getByTestId(`bullet-${f.agreementId}`)).toBeVisible();await page.getByRole('button',{name:'撤销上次处理',exact:true}).click();await expect(page.getByTestId(`bullet-${f.actionId}`)).toBeVisible();expect((await snap(request,f.eventId)).counts.needsDecisionCount).toBe(1);
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
test('joining preserves the related draft and completion stays independent of the open question',async({page,request},info)=>{
 const f=await fixtureFor(request);try{await open(page,f);await page.getByRole('button',{name:'加入跟进',exact:true}).click();await expect(page.getByRole('button',{name:/^完成：/})).toBeVisible();const w=await snap(request,f.eventId);expect(w.actions[0].id).toBe(f.actionId);expect(w.counts.needsDecisionCount).toBe(0);expect(w.bullets.find((b:{id:string})=>b.id===f.agreementId).reviewState).toBe('draft');await page.getByTestId(`intent-related-${f.intentCardId}`).getByText('相关记录 · AI 草稿',{exact:true}).click();await expect(page.getByText('约定向供应商询价',{exact:true})).toBeVisible();await page.getByRole('button',{name:/^完成：/}).click();await expect(page.getByRole('button',{name:/^重开：/})).toBeVisible();expect((await snap(request,f.eventId)).questions[0].resolutionState).toBe('open');await page.screenshot({path:info.outputPath('joined-intent-related-draft.png'),fullPage:true});await page.reload();await expect(page.getByRole('button',{name:/^重开：/})).toBeVisible();expect((await snap(request,f.eventId)).actions[0].id).toBe(f.actionId);
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
test('editing only the agreement in a mixed group keeps its corrected basis when joining later',async({page,request},info)=>{
 const f=await fixtureFor(request);try{await open(page,f);await page.getByRole('button',{name:'改记录',exact:true}).click();const record=page.getByTestId(`member-${f.agreementId}`),action=page.getByTestId(`member-${f.actionId}`);await expect(action.getByRole('option',{name:'加入跟进',exact:true})).toHaveCount(1);await expect(record.getByRole('option',{name:'确认',exact:true})).toHaveCount(1);await record.getByRole('textbox').fill('约定周五向供应商询价');await page.getByLabel('第2条修改来源',{exact:true}).selectOption('user_input');const box=await page.getByRole('button',{name:'保存本次选择',exact:true}).boundingBox();expect(box!.y+box!.height).toBeLessThanOrEqual(page.viewportSize()!.height);await page.screenshot({path:info.outputPath('mixed-intent-member-edit.png'),fullPage:false});await page.getByRole('button',{name:'保存本次选择',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByTestId(`bullet-${f.agreementId}`)).toContainText('约定周五');const current=await snap(request,f.eventId),ref=current.reviewCards.find((c:{id:string})=>c.id===f.intentCardId).sameIntent.recordRef;expect(current.counts.needsDecisionCount).toBe(0);expect(current.actions).toHaveLength(0);await page.getByRole('button',{name:'加入跟进',exact:true}).click();await expect(page.getByRole('button',{name:/^完成：/})).toBeVisible();expect((await snap(request,f.eventId)).actions[0].basisDetails.some((b:{acceptedRef:{claimVersionId:string}})=>b.acceptedRef.claimVersionId===ref.claimVersionId)).toBe(true);
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
test('declining the action through mixed member choices preserves the unreviewed agreement',async({page,request},info)=>{
 const f=await fixtureFor(request);try{await open(page,f);await page.locator(`#members-${f.intentCardId}`).click();await page.getByRole('button',{name:'同组逐条处理',exact:true}).click();await page.getByLabel('第1条处理方式',{exact:true}).selectOption('reject');await page.getByRole('button',{name:'保存本次选择',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByTestId(`bullet-${f.agreementId}`)).toContainText('AI 草稿');await expect(page.getByRole('button',{name:'加入跟进',exact:true})).toHaveCount(0);const w=await snap(request,f.eventId);expect(w.actions).toHaveLength(0);expect(w.counts.needsDecisionCount).toBe(0);await page.screenshot({path:info.outputPath('declined-action-kept-record.png'),fullPage:true});
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});

for(const kind of ['record','action'] as const)test(`same-intent ${kind} conflict stays one visible choice after resolving and undoing`,async({page,request},info)=>{
 const f=await fixtureFor(request,kind);try{
  await open(page,f);const row=page.locator(`[data-review-card="${f.intentCardId}"]`);await expect(row).toHaveCount(1);await expect(page.getByRole('button',{name:'核对新旧信息',exact:true})).toHaveCount(1);
  await page.getByRole('button',{name:'核对新旧信息',exact:true}).click();await page.getByRole('radio',{name:kind==='action'?/改为跟进新行动/:/采用新信息/}).check();const save=page.getByRole('button',{name:'保存选择',exact:true});const box=await save.boundingBox();expect(box!.y+box!.height).toBeLessThanOrEqual(page.viewportSize()!.height);await save.click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(row).toHaveCount(1);await expect(page.getByRole('button',{name:'核对新旧信息',exact:true})).toHaveCount(0);
  const w=await snap(request,f.eventId),group=w.reviewCards.find((c:{id:string})=>c.id===f.intentCardId);expect(group.members).toHaveLength(2);expect(group.sameIntent).toBeTruthy();expect(group.needsDecision).toBe(false);expect(w.actions.some((a:{id:string})=>a.id===f.actionId)).toBe(kind==='action');
  await page.screenshot({path:info.outputPath(`resolved-${kind}-intent.png`),fullPage:true});await page.reload();await expect(page.locator(`[data-review-card="${f.intentCardId}"]`)).toHaveCount(1);await page.getByRole('button',{name:'撤销上次处理',exact:true}).click();await expect(page.getByRole('button',{name:'核对新旧信息',exact:true})).toHaveCount(1);await expect(page.locator(`[data-review-card="${f.intentCardId}"]`)).toHaveCount(1);const restored=await snap(request,f.eventId);expect(restored.reviewCards.find((c:{id:string})=>c.id===f.intentCardId).members).toHaveLength(2);
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
