import {expect,test,type APIRequestContext,type Page} from '@playwright/test';
import {createLocalWorkflowFixture} from '../helpers/local-workflow-fixture.mjs';
async function fixtureFor(request:APIRequestContext,options:Parameters<typeof createLocalWorkflowFixture>[1]={}) {
 const projects=await (await request.get('/api/v1/projects')).json(),events=await (await request.get(`/api/v1/projects/${projects.data.projects[0].id}/events`)).json(),current=await (await request.get(`/api/v2/events/${events.data.events[0].id}/workspace`)).json();return createLocalWorkflowFixture(current.data.access.workspaceId,options);
}
async function open(page:Page,f:Awaited<ReturnType<typeof fixtureFor>>){await page.goto(`/?project=${f.projectId}&event=${f.eventId}&view=simple`);await expect(page.getByRole('button',{name:'复制记录',exact:true})).toBeVisible();}
async function conflict(page:Page,mode:'use_candidate'|'coexist') {await page.getByRole('button',{name:'核对新旧信息',exact:true}).click();await page.getByRole('radio',{name:mode==='use_candidate'?/采用新信息/:/两条信息分别适用/}).check();if(mode==='coexist')await page.getByRole('textbox',{name:'适用情况',exact:true}).fill('一期三十万，二期三十五万。');await page.getByRole('button',{name:'保存选择',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);}
async function inline(page:Page,id:string,text:string){await page.getByTestId(`bullet-${id}`).getByRole('button',{name:'改一下',exact:true}).click();await page.getByLabel('修改重点',{exact:true}).fill(text);await page.getByLabel('修改依据',{exact:true}).selectOption('user_input');}
const snap=async(request:APIRequestContext,eventId:string)=>(await (await request.get(`/api/v2/events/${eventId}/workspace`)).json()).data;

test('an accepted replacement has a working correction, explicit answer check, reload and undo',async({page,request},info)=>{
 const f=await fixtureFor(request,{withConflict:true,withFactAnswer:true});try{await open(page,f);await conflict(page,'use_candidate');await inline(page,f.newBudgetId!,'预算修正为三十六万，包含安装。');await page.getByRole('button',{name:'保存修改',exact:true}).click();await expect(page.getByRole('alert')).toContainText('请逐项选择');await page.getByLabel('第1个问题是否仍可回答',{exact:true}).selectOption('keep');await expect.poll(async()=>{const box=await page.getByRole('button',{name:'保存修改',exact:true}).boundingBox();return Boolean(box && box.y>=0 && box.y+box.height<=page.viewportSize()!.height);}).toBe(true);await page.screenshot({path:info.outputPath('replacement-correction.png'),fullPage:false});await page.getByRole('button',{name:'保存修改',exact:true}).click();await expect(page.getByTestId(`bullet-${f.newBudgetId}`)).toContainText('预算修正为三十六万');await expect(page.getByTestId(`bullet-${f.budgetId}`)).toHaveCount(0);await page.reload();await expect(page.getByTestId(`bullet-${f.newBudgetId}`)).toContainText('预算修正为三十六万');expect((await snap(request,f.eventId)).questions[0].resolutionState).toBe('resolved');await page.getByRole('button',{name:'撤销上次处理',exact:true}).click();await expect(page.getByTestId(`bullet-${f.newBudgetId}`)).toContainText('预算更新为三十五万');await expect(page.getByTestId(`bullet-${f.budgetId}`)).toHaveCount(0);
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
test('correcting a coexisting answer preserves its scope and only releases the chosen answer',async({page,request},info)=>{
 const f=await fixtureFor(request,{withConflict:true,withFactAnswer:true});try{await open(page,f);await conflict(page,'coexist');await inline(page,f.newBudgetId!,'二期预算修正为三十六万元。');await page.getByLabel('第1个问题是否仍可回答',{exact:true}).selectOption('reopen');await page.getByRole('button',{name:'保存修改',exact:true}).click();await expect(page.getByLabel('修改重点',{exact:true})).toHaveCount(0);const current=await snap(request,f.eventId);expect(current.questions[0].resolutionState).toBe('resolved');expect(current.questions[0].answerRefs.map((r:{claimId:string})=>r.claimId)).toEqual([f.budgetId]);await expect(page.getByTestId(`bullet-${f.newBudgetId}`)).toContainText('一期三十万，二期三十五万');await page.screenshot({path:info.outputPath('coexist-correction.png'),fullPage:true});await page.getByRole('button',{name:'撤销上次处理',exact:true}).click();await expect(page.getByTestId(`bullet-${f.newBudgetId}`)).toContainText('预算更新为三十五万');expect((await snap(request,f.eventId)).questions[0].answerRefs).toHaveLength(2);
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
test('a corrected result answer can be withdrawn while the action remains completed',async({page,request},info)=>{
 const f=await fixtureFor(request);try{await open(page,f);await page.getByRole('button',{name:'加入跟进',exact:true}).click();await page.getByRole('button',{name:'补结果',exact:true}).click();await page.getByLabel('补充答案',{exact:true}).fill('报价十二万元。');await page.getByLabel('同时标记行动完成',{exact:true}).check();await page.getByRole('button',{name:'保存结果',exact:true}).click();await expect(page.getByLabel('补充答案',{exact:true})).toHaveCount(0);await expect(page.getByText('报价十二万元。',{exact:true}).first()).toBeVisible();await expect(page.getByRole('button',{name:/^重开：/})).toBeVisible();const current=await snap(request,f.eventId),answer=current.questions[0].answerRefs[0];await inline(page,answer.claimId,'报价十三万元，包含运输。');await page.getByLabel('第1个问题是否仍可回答',{exact:true}).selectOption('keep');await page.getByRole('button',{name:'保存修改',exact:true}).click();await expect(page.getByTestId(`bullet-${answer.claimId}`)).toContainText('报价十三万元');await page.getByRole('button',{name:'撤回答案',exact:true}).click();await page.getByRole('button',{name:'确认撤回',exact:true}).click();await expect(page.getByTestId(`bullet-${answer.claimId}`)).toHaveCount(0);await expect(page.getByRole('button',{name:/^重开：/})).toBeVisible();await expect(page.getByRole('button',{name:'补答案',exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('corrected-answer-withdrawn.png'),fullPage:true});
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
test('a grouped accepted fact keeps its own question choice and leaves the other members visible',async({page,request},info)=>{
 const f=await fixtureFor(request,{withComposite:true,withFactAnswer:true});try{await open(page,f);await page.getByRole('button',{name:'同组逐条处理',exact:true}).click();await page.getByLabel('第1条处理方式',{exact:true}).selectOption('edit');await page.getByLabel('第1条修改内容',{exact:true}).fill('一期预算调整为三十一万元。');await page.getByLabel('第1条修改来源',{exact:true}).selectOption('user_input');await page.getByLabel('第1条第1个问题是否仍可回答',{exact:true}).selectOption('keep');await page.screenshot({path:info.outputPath('grouped-fact-review.png'),fullPage:false});await page.getByRole('button',{name:'保存本次选择',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByTestId(`bullet-${f.budgetId}`)).toContainText('一期预算调整为三十一万元');await expect(page.getByTestId(`bullet-${f.timeId}`)).toContainText('AI 草稿');expect((await snap(request,f.eventId)).questions[0].resolutionState).toBe('resolved');
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
test('access recovery preserves only the user fact edit and answer choice until current content is reviewed',async({page,request},info)=>{
 const f=await fixtureFor(request,{withFactAnswer:true});try{await open(page,f);await inline(page,f.budgetId!,'用户补充的预算三十一万元。');await page.getByLabel('第1个问题是否仍可回答',{exact:true}).selectOption('reopen');const route='**/api/v2/review-cards/*/decisions';await page.route(route,r=>r.fulfill({status:403,contentType:'application/json',body:JSON.stringify({error:{code:'FORBIDDEN',message:'当前访问已失效'}})}));await page.getByRole('button',{name:'保存修改',exact:true}).click();await expect(page.getByLabel('保留的修改重点1')).toHaveValue('用户补充的预算三十一万元。');await expect(page.getByText('预算大约三十万',{exact:true})).toHaveCount(0);await page.unroute(route);await page.getByRole('button',{name:'恢复读取',exact:true}).click();await expect(page.getByLabel('修改重点',{exact:true})).toHaveValue('用户补充的预算三十一万元。');await expect(page.getByLabel('第1个问题是否仍可回答',{exact:true})).toHaveValue('reopen');await expect(page.getByRole('button',{name:'保存修改',exact:true})).toBeDisabled();await page.getByRole('button',{name:'核对后采用当前版本',exact:true}).click();await page.screenshot({path:info.outputPath('fact-access-recovery.png'),fullPage:false});await page.getByRole('button',{name:'保存修改',exact:true}).click();await expect(page.getByRole('button',{name:'补答案',exact:true})).toBeVisible();
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});

test('undo restores the original action basis without another review and keeps completion',async({page,request},info)=>{
 const f=await fixtureFor(request,{withBudgetBasis:true});try{
  await open(page,f);await page.getByRole('button',{name:'加入跟进',exact:true}).click();await page.getByRole('button',{name:/^完成：/}).click();
  await expect(page.getByRole('button',{name:/^重开：/})).toBeVisible();await inline(page,f.budgetId!,'预算改为三十六万元。');
  await page.getByRole('button',{name:'保存修改',exact:true}).click();await expect(page.getByTestId(`bullet-${f.budgetId}`)).toContainText('预算改为三十六万元');
  expect((await snap(request,f.eventId)).actions[0].basisState).toBe('needs_review');
  await page.getByRole('button',{name:'撤销上次处理',exact:true}).click();await expect(page.getByTestId(`bullet-${f.budgetId}`)).toContainText('预算大约三十万');
  expect((await snap(request,f.eventId)).actions[0].basisState).toBe('current');await expect(page.getByRole('button',{name:/^重开：/})).toBeVisible();
  await page.reload();await expect(page.getByRole('button',{name:'复制记录',exact:true})).toBeVisible();await expect(page.getByTestId(`bullet-${f.budgetId}`)).toContainText('预算大约三十万');await expect(page.getByRole('button',{name:/^重开：/})).toBeVisible();await expect(page.getByRole('button',{name:'核对依据',exact:true})).toHaveCount(0);expect((await snap(request,f.eventId)).actions[0].basisState).toBe('current');await page.screenshot({path:info.outputPath('undo-original-action-basis.png'),fullPage:true});
 }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
