import {expect,test,type APIRequestContext,type Page} from '@playwright/test';
import {createLocalWorkflowFixture} from '../helpers/local-workflow-fixture.mjs';
async function fixtureFor(request:APIRequestContext) {
  const projects=await (await request.get('/api/v1/projects')).json();const events=await (await request.get(`/api/v1/projects/${projects.data.projects[0].id}/events`)).json();const current=await (await request.get(`/api/v2/events/${events.data.events[0].id}/workspace`)).json();return createLocalWorkflowFixture(current.data.access.workspaceId);
}
async function open(page:Page,f:Awaited<ReturnType<typeof fixtureFor>>){await page.goto(`/?project=${f.projectId}&event=${f.eventId}&view=simple`);await expect(page.getByRole('button',{name:'复制记录',exact:true})).toBeVisible();}
async function complete(page:Page){await page.getByRole('button',{name:'加入跟进',exact:true}).click();await page.getByRole('button',{name:'补结果',exact:true}).click();await page.getByLabel('补充答案',{exact:true}).fill('含税安装费十二万元。');await page.getByLabel('同时标记行动完成',{exact:true}).check();await page.getByRole('button',{name:'保存结果',exact:true}).click();await expect(page.getByRole('button',{name:/^重开：/})).toBeVisible();}
async function edit(page:Page,mode:'keep'|'reopen'){await page.getByRole('button',{name:'调整问题',exact:true}).click();await page.getByLabel('修改问题',{exact:true}).fill('含税且包含安装的费用是多少？');await page.getByLabel('问题修改依据',{exact:true}).selectOption('user_input');await page.getByLabel('第1条答案是否适用',{exact:true}).selectOption(mode);}

test('retained answers follow the new question and withdrawing their result reopens it while completion stays',async({page,request},info)=>{
  const f=await fixtureFor(request);try{await open(page,f);await complete(page);await edit(page,'keep');const dialog=page.getByRole('dialog');await expect(dialog).toContainText('完成状态保留');
    const button=dialog.getByRole('button',{name:'保存问题修改',exact:true});const bounds=await button.boundingBox();expect(bounds!.y+bounds!.height).toBeLessThanOrEqual(page.viewportSize()!.height);await page.screenshot({path:info.outputPath('question-retain-review.png'),fullPage:false});await button.click();await expect(dialog).toHaveCount(0);
    await expect(page.getByText('对应问题：含税且包含安装的费用是多少？',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:/^重开：/})).toBeVisible();await expect(page.getByRole('button',{name:'核对依据',exact:true}).first()).toBeVisible();
    const current=(await (await request.get(`/api/v2/events/${f.eventId}/workspace`)).json()).data;expect(current.questions[0].resolutionState).toBe('resolved');expect(current.actions[0].questionRefs[0].claimVersionId).toBe(current.questions[0].claimRef.claimVersionId);
    await page.getByRole('button',{name:'撤回答案',exact:true}).click();await page.getByRole('button',{name:'确认撤回',exact:true}).click();await expect(page.getByTestId(`bullet-${f.questionId}`)).toContainText('含税且包含安装的费用是多少？');await expect(page.getByRole('button',{name:/^重开：/})).toBeVisible();await expect(page.getByRole('button',{name:'补答案',exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('question-retain-withdraw.png'),fullPage:true});
  }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
test('reopening a corrected question removes its answer and undo restores the whole previous state',async({page,request},info)=>{
  const f=await fixtureFor(request);try{await open(page,f);await complete(page);await edit(page,'reopen');await page.getByRole('button',{name:'保存问题修改',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByTestId(`bullet-${f.questionId}`)).toContainText('含税且包含安装的费用是多少？');await expect(page.getByRole('button',{name:'补答案',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:/^重开：/})).toBeVisible();await page.screenshot({path:info.outputPath('question-reopen.png'),fullPage:true});
    const current=(await (await request.get(`/api/v2/events/${f.eventId}/workspace`)).json()).data;expect(current.questions[0].answerRefs).toHaveLength(0);
    await page.getByRole('button',{name:'撤销上次处理',exact:true}).click();await expect(page.getByText('对应问题：费用是多少？',{exact:true})).toBeVisible();await expect(page.getByTestId(`bullet-${f.questionId}`)).toHaveCount(0);await expect(page.getByRole('button',{name:/^重开：/})).toBeVisible();
  }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
test('an unanswered question has a simple edit and can immediately receive an answer',async({page,request},info)=>{
  const f=await fixtureFor(request);try{await open(page,f);await page.getByRole('button',{name:'调整问题',exact:true}).click();await page.getByLabel('修改问题',{exact:true}).fill('含税安装费用是多少？');await page.getByLabel('问题修改依据',{exact:true}).selectOption('user_input');await expect(page.getByLabel('第1条答案是否适用')).toHaveCount(0);await page.getByRole('button',{name:'保存问题修改',exact:true}).click();await expect(page.getByTestId(`bullet-${f.questionId}`)).toContainText('含税安装费用是多少？');await page.getByRole('button',{name:'补答案',exact:true}).click();await page.getByLabel('补充答案',{exact:true}).fill('十三万元。');await page.getByRole('button',{name:'保存答案',exact:true}).click();await expect(page.getByTestId(`bullet-${f.questionId}`)).toHaveCount(0);await expect(page.getByText('对应问题：含税安装费用是多少？',{exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('question-simple-answer.png'),fullPage:true});
  }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
test('a concurrent new answer preserves question text and requires review of the new answer',async({page,request},info)=>{
  const f=await fixtureFor(request);try{await open(page,f);await complete(page);await edit(page,'keep');const current=(await (await request.get(`/api/v2/events/${f.eventId}/workspace`)).json()).data,q=current.questions[0];
    const res=await request.post(`/api/v2/questions/${q.id}/answers`,{headers:{'Idempotency-Key':crypto.randomUUID()},data:{expectedContextVersion:current.contextVersion,expectedQuestionRevision:q.revision,answerText:'新的含税报价十三万元。',evidenceRefs:[],answerDecision:{mode:'replace',priorAnswerRefs:q.answerRefs}}});expect(res.ok()).toBe(true);
    await page.getByRole('button',{name:'保存问题修改',exact:true}).click();await expect(page.getByRole('button',{name:'核对后采用当前版本',exact:true})).toBeVisible();await expect(page.getByLabel('修改问题',{exact:true})).toHaveValue('含税且包含安装的费用是多少？');await page.getByRole('button',{name:'核对后采用当前版本',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('新的含税报价十三万元。');await expect(page.getByLabel('第1条答案是否适用')).toHaveValue('');await page.screenshot({path:info.outputPath('question-concurrent-review.png'),fullPage:false});await page.getByLabel('第1条答案是否适用').selectOption('keep');await page.getByRole('button',{name:'保存问题修改',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
  }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
test('permission recovery keeps only the user question edit and answer choice until latest content is reviewed',async({page,request},info)=>{
  const f=await fixtureFor(request);try{await open(page,f);await complete(page);await edit(page,'keep');const route='**/api/v2/review-cards/*/decisions';await page.route(route,r=>r.fulfill({status:403,contentType:'application/json',body:JSON.stringify({error:{code:'FORBIDDEN',message:'当前访问已失效'}})}));await page.getByRole('button',{name:'保存问题修改',exact:true}).click();await expect(page.getByLabel('保留的修改问题1')).toHaveValue('含税且包含安装的费用是多少？');await expect(page.getByText('含税安装费十二万元。',{exact:true})).toHaveCount(0);await expect(page.getByRole('dialog')).toHaveCount(0);await page.unroute(route);await page.getByRole('button',{name:'恢复读取',exact:true}).click();await expect(page.getByLabel('修改问题',{exact:true})).toHaveValue('含税且包含安装的费用是多少？');await expect(page.getByLabel('第1条答案是否适用')).toHaveValue('keep');await expect(page.getByRole('button',{name:'保存问题修改',exact:true})).toBeDisabled();const content=page.getByRole('region',{name:'问题与答案',exact:true});await content.hover();await page.mouse.wheel(0,600);await expect.poll(async()=>{const answerBounds=await page.getByLabel('第1条答案是否适用').boundingBox();const contentBounds=await content.boundingBox();return Boolean(answerBounds && contentBounds && answerBounds.y>=contentBounds.y && answerBounds.y+answerBounds.height<=contentBounds.y+contentBounds.height);}).toBe(true);const saveBounds=await page.getByRole('button',{name:'保存问题修改',exact:true}).boundingBox();expect(saveBounds!.y+saveBounds!.height).toBeLessThanOrEqual(page.viewportSize()!.height);await page.screenshot({path:info.outputPath('question-recovery-review.png'),fullPage:false});await page.getByRole('button',{name:'核对后采用当前版本',exact:true}).click();await page.getByRole('button',{name:'保存问题修改',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.screenshot({path:info.outputPath('question-access-restored.png'),fullPage:true});
  }finally{await page.close({runBeforeUnload:false}).catch(()=>undefined);f.cleanup();}
});
